version: '3.7'

services:
  # Sample api.
  sample:
    build:
      context: ..
      dockerfile: ./build/docker/sample/Dockerfile
    image: sample_local
    container_name: sample
    tty: true
    volumes:
      - ../go.mod:/app/go.mod
      - ../go.sum:/app/go.sum
      - ../cmd/sample:/app/sample/cmd
      - ../internal/sample:/app/sample/internal
      - ../pkg/sample:/app/sample/pkg
      - ../test/sample:/app/sample/test
      - ../tools:/app/sample/tools
      - ../api/sample:/app/sample/api
    ports:
      - "8090:8080"
    command: "sh -c \"reflex -sr '(.go$$|go\\.mod)' -- go run ./cmd/main.go\""
    restart: always 
    